### ISSUE TITLE
Cadastro de usuários e autenticação

### ISSUE THREAD

**Issue by huandersonlima** [ThierryMatheus/FiqueAlerta#1]
- [x] Cadastro do usuário
(definir quais dados serão solicitados)
- [x]  Mecanismo de validação de cadastro
- [x] Tela de autenticação do sistema (Entrar/Cadastrar). Esqueceu a senha? Primeiro acesso?
- [x]  Definir a arquitetura de autenticação no sistema.
