### ISSUE TITLE
Cadastro da denúncia

### ISSUE THREAD

**Issue by gustavojms** [ThierryMatheus/FiqueAlerta#2]
- [x] Cadastro da denúncia
- [x] Definição de quais dados serão necessários
- [x] Mecanismo de validação
