### ISSUE TITLE
Modificação visual do sistema

### ISSUE THREAD

**Issue by gustavojms** [ThierryMatheus/FiqueAlerta#34]
Modificação visual em todas as páginas do sistema utilizando o padrão adotado na prototipagem feita por membros da equipe.

- [x] Tela inicial.
- [x] Tela para entrar no sistema.
- [x] Tela de cadastro inicial (Dados básicos do usuário).
- [x] Telas de cadastro (Escolha do tipo de usuário, complementar perfil, cadastro de empresa).
- [x] Tela inicial dentro do sistema.

**Comment by gustavojms** [comment]
Modificação da tela inicial realizada na issue #35

**Comment by gustavojms** [comment]
Modificação da tela de login e de cadastro inicial realizada na issue #36

**Comment by gustavojms** [comment]
Tela para escolha do tipo do usuário e tela do cadastro da empresa realizadas na issue #38

**Comment by gustavojms** [comment]
Tela inicial dentro do sistema realizada na issue #39
