### ISSUE TITLE
Integração da API do Google Maps

### ISSUE THREAD

**Issue by gustavojms** [ThierryMatheus/FiqueAlerta#41]
Integração da API do Google Maps dentro do sistema.

Quais credenciais serão necessárias para ter acesso à API?
Como funciona a implementação no back-end?
Como funciona para fazer a implementação juntamente com o front-end?

- [x] Estudo sobre a API.
- [x] Implementar no sistema.
- [x] Implementar na tela de denúncias.
- [x] Testar funcionalidade.

**Comment by gustavojms** [comment]
Documentação do Google Maps: https://developers.google.com/maps/documentation/javascript/overview#Inline
