### ISSUE TITLE
[EPIC] Implementar banco de dados

### ISSUE THREAD

**Issue by EsdrasPedro** [ThierryMatheus/FiqueAlerta#8]
Criar um banco de dados para armazenar dados cadastrais e as denúncias no sistema.

- [x] Criar Modelo Conceitual
- [x] Criar Modelo Lógico
- [x] Criar Modelo físico
