### ISSUE TITLE
Cadastro do Reclamante

### ISSUE THREAD

**Issue by Gjss333** [ThierryMatheus/FiqueAlerta#9]
**Como** Reclamante,
**Quero** me cadastrar no sistema
**Para** relatar denúncias e poder acompanhar a resolução do problema.

- [x] Criar o protótipo da tela no Figma;
- [x] Implementar back-end do cadastro;
- [x]  Criar a view de cadastro do Reclamante;
- [x]  Testar a funcionalidade.

**Comment by huandersonlima** [comment]
Model e migration criados nas issues #19 e #20 respectivamente

**Comment by huandersonlima** [comment]
Controller e view criados na issue #26
